name: Java CI/CD with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_IP }} $(ssh-keyscan -H ${{ secrets.SERVER_IP }} 2>/dev/null)" >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          cat > .env <<EOL
          EOL
          ssh $SERVER_USER@$SERVER_IP << 'EOF'
            # Установка зависимостей (если их нет)
            if ! command -v docker &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl enable docker
              sudo systemctl start docker
            fi

            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Работа с репозиторием
            if [ -d "ne-hackathon" ]; then
              cd ne-hackathon
              git pull origin main
            else
              git clone https://github.com/Dema-koder/ne-hackathon.git
              cd ne-hackathon
            fi
          EOF
          
          scp .env $SERVER_USER@$SERVER_IP:~/ne-hackathon/.env
          
          ssh $SERVER_USER@$SERVER_IP << 'EOF'
            cd ~/ne-hackathon
            sudo docker-compose down || true
            sudo docker-compose up -d --build
          EOF
          
          rm -f .env